plugins {
    id 'com.android.application'
}

android {
    namespace 'org.zet.zov'
    compileSdk 34

    defaultConfig {
        applicationId "org.zet.zov"
        minSdk 24
        targetSdk 28
        versionCode 45
        versionName "1.6.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'org.apache.commons:commons-compress:1.26.1'
    implementation 'org.tukaani:xz:1.9'
}
